#!/bin/bash
#	markcheck  3.37.178  2018-08-04_13:08:38_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.36  
#	   got currect release number #29 
#	markcheck  3.36.177  2018-08-03_14:47:51_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.35  
#	   move change to github to switch another system to work #29 
#	markcheck  3.35.176  2018-08-03_14:32:18_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.34  
#	   need to pull the FILE_NAME out of the command line earlier in the script #29 
#	markcheck  3.34.175  2018-08-03_14:17:47_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.33  
#	   got curl to down load reposiroty #29 
#	markcheck  3.33.174  2018-08-03_13:56:48_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.32  
#	   start working on curl statement #29 
#	markcheck  3.32.173  2018-08-03_12:02:39_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.31  
#	   clean up debugging #29 
#	markcheck  3.31.172  2018-08-03_11:09:26_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.30  
#	   updated display_help #29 
#	markcheck  3.30.171  2018-08-03_10:37:26_CDT  https://github.com/BradleyA/markit  bradley  zero.cptx86.com 3.29  
#	   complete testing of --file -f #29 
#	markcheck  3.29.170  2018-08-02_23:18:07_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.28  
#	   need more work but close #29 
#	markcheck  3.28.169  2018-08-02_23:08:58_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.27  
#	   parsed MARKIT_FILE now put it into one line with error detction #29 
#	markcheck  3.27.168  2018-08-02_15:22:11_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.26  
#	   process command arguments #29 
#	markcheck  3.26.167  2018-08-02_13:57:07_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.25  
#	   found working directory of file 
#	markcheck  3.25.166  2018-08-02_13:45:32_CDT  https://github.com/BradleyA/markit  uadmin  three-rpi3b.cptx86.com 3.24  
#	   create new script to check if the current installed version is the latest version #29 
###
#	set -x
#	set -v
###
display_help() {
echo -e "\n${0} - AFTER DESIGN NEED TO COMPLETE HELP SECTION"
echo -e "\nUSAGE\n   ${0} [<file_name>]"
echo    "   ${0} [--file <path>/<file_name> | -f <path>/<file_name>]"
echo    "   ${0} [--help | -help | help | -h | h | -? | ?] [--version | -v]"
echo -e "\nDESCRIPTION\nXXXX"
echo -e "\nxxxxx"
echo -e "\nOPTIONS\n   "
echo -e "\nDOCUMENTATION\n   https://github.com/BradleyA/markit"
echo -e "\nEXAMPLES\n  "
}
if [ "$1" == "--help" ] || [ "$1" == "-help" ] || [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "h" ] || [ "$1" == "-?" ] || [ "$1" == "?" ] ; then
	display_help
	exit 0
fi
if [ "$1" == "--version" ] || [ "$1" == "-version" ] || [ "$1" == "version" ] ||  [ "$1" == "-v" ] ; then
	head -2 ${0} | awk {'print$2"\t"$3'}
	exit 0
fi
###
BOLD=$(tput bold)
NORMAL=$(tput sgr0)
#	Check if in Git repository
source /usr/share/bash-completion/completions/git
if ! $( __gitdir > /dev/null 2>&1 ) ; then
	echo -e "${NORMAL}${0} ${LINENO} [${BOLD}WARNING${NORMAL}]:	`pwd` Check if you are in a Git repository\n\tand you have GIT permission.\n"	1>&2
	exit 0
fi
#	Check if remote git repository has been setup #28
git rev-list HEAD 1> /dev/null || { echo -e "\n${NORMAL}${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:	Remote repository has\n\tnot been setup or git cloned <remote-repository> was not used to pull\n\tremote repository before using markit." ; exit 1; }
#       Check if argument 1 is blank
if [ "${1}" == "" ] ; then
	display_help
	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  File not found on command line\n" 1>&2
	exit 0
fi
#	Check if argument 1 is -f or --file the path is reqired to be included 
if [ "${1}" == "--file" ] || [ "${1}" == "-f" ] ; then
	#       Check if argument 2 is blank
	if [ "${2}" == "" ] ; then
		display_help
		echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  File name not found; --file <path>/<file_name> or -f <path>/<file_name> option\n" 1>&2
		exit 0
	fi
	MARKIT_FILE=${2}
else
	#	Locate file in the PATH
	TEMP=`whereis "${1}"`
	MARKIT_FILE=$(echo ${TEMP} | awk {'print $2'} )
	#       Check if TEMP is blank
	if [ "${MARKIT_FILE}" == "" ] ; then
		display_help
		echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${1} not found; consider using --file <path>/<file_name> or -f <path>/<file_name> option\n" 1>&2
		exit 0
	fi
fi
FILE_NAME=`echo ${MARKIT_FILE} | sed 's/.*\///'`
###############################
echo  "${LINENO} MARKIT_FILE = ${MARKIT_FILE}    FILE_NAME = ${FILE_NAME}"
echo  "${LINENO} Does it include the path for MARKIT_FILE = ${MARKIT_FILE}"
###############################
#       Check if file exists and has a size greater than zero || if file exists and is readable
if [ ! -s ${MARKIT_FILE} ] || [ ! -r ${MARKIT_FILE} ] ; then
       	echo -e "${NORMAL}\n${0} ${LINENO} [${BOLD}ERROR${NORMAL}]:  ${MARKIT_FILE} file is not found or is empty or is not readable\n" 1>&2
	exit 1
fi
###############################
echo  "${LINENO} MARKIT_FILE is found and is not empty and is it readable ? = ${MARKIT_FILE}"
echo  "${LINENO} REPOSITORY_NAME >>${REPOSITORY_NAME}<<"
###############################
#	REPOSITORY_NAME=`head -2 ${MARKIT_FILE} | awk {'print$5'}`
#	MARKIT_FILE_RELEASE=`head -2 ${MARKIT_FILE} | awk {'print$3'}`
REPOSITORY_NAME=`grep -m 1 -e ${FILE_NAME} -e git ${MARKIT_FILE} | awk {'print$5'}`
MARKIT_FILE_RELEASE=`grep -m 1 -e ${FILE_NAME} -e git ${MARKIT_FILE} | awk {'print$3'}`
###
echo  "${LINENO} MARKIT_FILE_RELEASE >>${MARKIT_FILE_RELEASE}<<"
echo  "${LINENO} REPOSITORY_NAME >>${REPOSITORY_NAME}<<"
REPOSITORY_NAME=`echo ${REPOSITORY_NAME} | sed 's/github.com/api.github.com\/repos/'`
echo  ">>${LINENO} REPOSITORY_NAME >>${REPOSITORY_NAME}<<"
REPOSITORY_NAME="curl \-L ${REPOSITORY_NAME}/tarball | tar --directory /tmp/markit-temp -xzf - "
echo  "${LINENO} REPOSITORY_NAME >>${REPOSITORY_NAME}"
###
mkdir /tmp/markit-temp
eval ${REPOSITORY_NAME}
###
#	need to strip the file name out of ${MARKIT_FILE} to be used with the find below
###
FILE_NAME_LOCATION=`find /tmp/markit-temp -type f -name ${FILE_NAME} -print`
echo ${FILE_NAME_LOCATION}
MARKIT_FILE_CURRENT_RELEASE=`grep -m 1 -e ${FILE_NAME} -e git ${FILE_NAME_LOCATION} | awk {'print$3'}`
#	MARKIT_FILE_CURRENT_RELEASE=`head -2 ${FILE_NAME_LOCATION} | awk {'print$3'}`
echo  "${LINENO} MARKIT_FILE_CURRENT_RELEASE >>${MARKIT_FILE_CURRENT_RELEASE}<<"
###
rm -rf /tmp/markit-temp
###
