##############################333
#		dummy/sample.MK	3.3.95	2018-02-12_15:43:06_CST uadmin six-rpi3b.cptx86.com 3.3-9-gad9d812 
#		beta 3.3 for #5 
#		sample.MK	3.3.85	2018-02-12_00:23:05_CST uadmin six-rpi3b.cptx86.com 3.2-4-g95418e1 
#		testing x x.MK x.h x.sh for #5 



#		sample.MK	3.2.84	2018-02-12_00:18:10_CST uadmin six-rpi3b.cptx86.com 3.2-3-g270e96e 
#		testing x x.MK x.h x.sh for #5 



#		sample.MK	3.2.83	2018-02-12_00:12:34_CST uadmin six-rpi3b.cptx86.com 3.2-2-g6d8266e 
#		testing x x.MK x.h x.sh for #5 

#	sample.MK	3.1.74	2018-02-11_21:35:56_CST uadmin six-rpi3b.cptx86.com 1.6-32-g232fc5f 
#	Testing failed git push login 
