######################
#	testfiles/dockerfile	3.4.108	2018-02-13_10:42:28_CST uadmin six-rpi3b.cptx86.com 3.4-5-ga1543ee 
#	   change two tabs to one tab in case statement using # 
#		dockerfile	3.3.101	2018-02-12_21:36:19_CST uadmin six-rpi3b.cptx86.com 3.3-15-g5487050 
#		Test for dockerfile, closes #12 
FROM busybox:latest
LABEL MAINTAINER Some One
CMD ["echo 'Hello World'"]
